apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notebook
parameters:
  - name: NOTEBOOK_NAME
    required: true
  - name: RUN_NAME
    required: true
  - name: USERNAME
    required: true
  - name: IMAGE_NAME
    required: true
  - name: NAMESPACE
    required: true
  - name: OPENSHIFT_URL
    required: true
  - name: USER
    required: true
  - name: IMAGE_REPO
    required: true
    value: "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications"
  - name: HUB_HOST
    required: true
  - name: PVC_SIZE
    required: true
    value: "20Gi"
  - name: TOKEN
    required: false
objects:
  - apiVersion: kubeflow.org/v1beta1
    kind: Notebook
    metadata:
      name: ${NOTEBOOK_NAME}
      labels:
        ope-run: ${RUN_NAME}
        app: ${NOTEBOOK_NAME}
        opendatahub.io/dashboard: "true"
        opendatahub.io/odh-managed: "true"
        opendatahub.io/user: ${USER}
      annotations:
        notebooks.opendatahub.io/inject-oauth: "true"
        notebooks.opendatahub.io/last-image-selection: ${IMAGE_NAME}
        notebooks.opendatahub.io/last-size-selection: Small
        notebooks.opendatahub.io/oauth-logout-url: "${OPENSHIFT_URL}/${NAMESPACE}?notebookLogout=${NOTEBOOK_NAME}"
        opendatahub.io/username: ${USER}
        openshift.io/description: ""
        openshift.io/display-name: ${NOTEBOOK_NAME}
        opendatahub.io/image-display-name: ${IMAGE_NAME}
    spec:
      # Avoid GPU nodes by default; set values: ['true'] to prefer GPU nodes instead
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "false"
      template:
        spec:
          serviceAccountName: ${NOTEBOOK_NAME}
          enableServiceLinks: false
          containers:
            - name: ${NOTEBOOK_NAME}
              image: ${IMAGE_REPO}/${IMAGE_NAME}:latest
              imagePullPolicy: Always
              workingDir: /opt/app-root/src
              ports:
                - containerPort: 8888
                  name: notebook-port
                  protocol: TCP
              env:
                - name: NOTEBOOK_ARGS
                  value: |
                    --ServerApp.port=8888
                    --ServerApp.token=${TOKEN}
                    --ServerApp.password=''
                    --ServerApp.base_url=/notebook/${NAMESPACE}/${NOTEBOOK_NAME}
                    --ServerApp.quit_button=False
                    --ServerApp.tornado_settings={"user":"${USER}","hub_host":"${HUB_HOST}","hub_prefix":"projects/${NAMESPACE}"}
                - name: JUPYTER_IMAGE
                  value: ${IMAGE_REPO}/${IMAGE_NAME}:latest
              resources:
                limits:
                  cpu: "2"
                  memory: 8Gi
                requests:
                  cpu: "1"
                  memory: 8Gi
              readinessProbe:
                httpGet:
                  path: /notebook/${NAMESPACE}/${NOTEBOOK_NAME}/api
                  port: notebook-port
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /notebook/${NAMESPACE}/${NOTEBOOK_NAME}/api
                  port: notebook-port
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
              volumeMounts:
                - name: ${NOTEBOOK_NAME}
                  mountPath: /opt/app-root/src
                - name: shm
                  mountPath: /dev/shm
            - name: oauth-proxy
              image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
              imagePullPolicy: Always
              ports:
                - containerPort: 8443
                  name: oauth-proxy
                  protocol: TCP
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              args:
                - "--provider=openshift"
                - "--https-address=:8443"
                - "--http-address="
                - "--openshift-service-account=${NOTEBOOK_NAME}"
                - "--cookie-secret-file=/etc/oauth/config/cookie_secret"
                - "--cookie-expire=24h0m0s"
                - "--tls-cert=/etc/tls/private/tls.crt"
                - "--tls-key=/etc/tls/private/tls.key"
                - "--upstream=http://localhost:8888"
                - "--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                - "--email-domain=*"
                - "--skip-provider-button"
                - >-
                  --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"${NOTEBOOK_NAME}","namespace":"${NAMESPACE}"}
                - "--logout-url=${OPENSHIFT_URL}/${NAMESPACE}?notebookLogout=${NOTEBOOK_NAME}"
              readinessProbe:
                httpGet:
                  path: /oauth/healthz
                  port: oauth-proxy
                  scheme: HTTPS
                initialDelaySeconds: 5
                periodSeconds: 5
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /oauth/healthz
                  port: oauth-proxy
                  scheme: HTTPS
                initialDelaySeconds: 30
                periodSeconds: 5
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
              volumeMounts:
                - name: oauth-config
                  mountPath: /etc/oauth/config
                - name: tls-certificates
                  mountPath: /etc/tls/private
          volumes:
            - name: ${NOTEBOOK_NAME}
              persistentVolumeClaim:
                claimName: ${NOTEBOOK_NAME}
            - name: shm
              emptyDir:
                medium: Memory
            - name: oauth-config
              secret:
                secretName: ${NOTEBOOK_NAME}-oauth-config
                defaultMode: 420
            - name: tls-certificates
              secret:
                secretName: ${NOTEBOOK_NAME}-tls
                defaultMode: 420
